version: "3.7"

networks:
  book-lib-microservice:
    name: book-lib-microservice
    driver: bridge

services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "${API_GATEWAY_PPROF_HTTP_PUBLISH_PORT}:${API_GATEWAY_PPROF_HTTP_PORT}"
      - "${API_GATEWAY_HTTP_PUBLISH_PORT}:${API_GATEWAY_HTTP_PORT}"
    env_file:
      - api-gateway/.docker.env
    networks:
      - book-lib-microservice
    depends_on:
      - user-service
      - book-service
      - lending-service

  user-service:
    build:
      context: ./user-service
    ports:
      - "${USER_SERVICE_PPROF_HTTP_PUBLISH_PORT}:${USER_SERVICE_PPROF_HTTP_PORT}"
      - "${USER_SERVICE_GRPC_PUBLISH_PORT}:${USER_SERVICE_GRPC_PORT}"
    env_file:
      - user-service/.docker.env
    networks:
      - book-lib-microservice
    depends_on:
      - mongo

  book-service:
    build:
      context: ./book-service
    ports:
      - "${BOOK_SERVICE_PPROF_HTTP_PUBLISH_PORT}:${BOOK_SERVICE_PPROF_HTTP_PORT}"
      - "${BOOK_SERVICE_GRPC_PUBLISH_PORT}:${BOOK_SERVICE_GRPC_PORT}"
    env_file:
      - book-service/.docker.env
    networks:
      - book-lib-microservice
    depends_on:
      - mongo

  lending-service:
    build:
      context: ./lending-service
    ports:
      - "${LENDING_SERVICE_PPROF_HTTP_PUBLISH_PORT}:${LENDING_SERVICE_PPROF_HTTP_PORT}"
      - "${LENDING_SERVICE_GRPC_PUBLISH_PORT}:${LENDING_SERVICE_GRPC_PORT}"
    env_file:
      - lending-service/.docker.env
    networks:
      - book-lib-microservice
    depends_on:
      - mongo
      - book-service

  mongo:
    image: mongo:4.2
    ports:
      - "${MONGO_PUBLISH_PORT}:${MONGO_PORT}"
    command: mongod
    networks:
      - book-lib-microservice
