version: "3.7"

networks:
  book-lib-microservice:
    name: book-lib-microservice
    driver: bridge

services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - '8000:8000'
    environment:
      HTTP_PORT: ':8000'
      JWT_SECRET_KEY: 'secret'
      USER_SERVICE_HOST: 'user-service'
      USER_SERVICE_PORT: ':8000'
      BOOK_SERVICE_HOST: 'book-service'
      BOOK_SERVICE_PORT: ':8000'
      LENDING_SERVICE_HOST: 'lending-service'
      LENDING_SERVICE_PORT: ':8000'
    networks:
      - book-lib-microservice
    depends_on:
      - user-service
      - book-service
      - lending-service

  user-service:
    build:
      context: ./user-service
    ports:
      - '3000:8000'
    environment:
      GRPC_PORT: ':8000'
      JWT_SECRET_KEY: 'secret'
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'user-service'
      ADMIN_EMAIL: 'admin@lib.com'
      LIBRARIAN_EMAIL: 'librarian@lib.com'
      MEMBER_EMAIL: 'member@lib.com'
      DEFAULT_USER_PASSWORD: 'lib'
    networks:
      - book-lib-microservice
    depends_on:
      - mongo

  book-service:
    build:
      context: ./book-service
    ports:
      - '3001:8000'
    environment:
      GRPC_PORT: ':8000'
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'book-service'
    networks:
      - book-lib-microservice
    depends_on:
      - mongo

  lending-service:
    build:
      context: ./lending-service
    ports:
      - '3002:8000'
    environment:
      GRPC_PORT: ':8000'
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'lending-service'
      USER_SERVICE_HOST: 'user-service'
      USER_SERVICE_PORT: ':8000'
      BOOK_SERVICE_HOST: 'book-service'
      BOOK_SERVICE_PORT: ':8000'
    networks:
      - book-lib-microservice
    depends_on:
      - mongo
      - book-service

  mongo:
    image: mongo:4.2
    ports:
      - '37017:27017'
    command: mongod
    networks:
      - book-lib-microservice
