version: "3.7"

networks:
  book-lib-microservice:
    name: book-lib-microservice
    driver: bridge

services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "6000:6060"
      - "8000:8000"
    env_file:
      - api-gateway/.docker.env
    networks:
      - book-lib-microservice
    depends_on:
      - user-service
      - book-service
      - lending-service

  user-service:
    build:
      context: ./user-service
    ports:
      - "6060:6060"
      - "3000:8000"
    env_file:
      - user-service/.docker.env
    networks:
      - book-lib-microservice
    depends_on:
      - mongo

  book-service:
    build:
      context: ./book-service
    ports:
      - "6061:6060"
      - "3001:8000"
    env_file:
      - book-service/.docker.env
    networks:
      - book-lib-microservice
    depends_on:
      - mongo

  lending-service:
    build:
      context: ./lending-service
    ports:
      - "6062:6060"
      - "3002:8000"
    env_file:
      - lending-service/.docker.env
    networks:
      - book-lib-microservice
    depends_on:
      - mongo
      - book-service

  mongo:
    image: mongo:4.2
    ports:
      - "37017:27017"
    command: mongod
    networks:
      - book-lib-microservice
