// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: lending.proto

package proto

import (
	context "context"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLendingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookId string `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *CreateLendingRequest) Reset() {
	*x = CreateLendingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lending_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLendingRequest) ProtoMessage() {}

func (x *CreateLendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lending_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLendingRequest.ProtoReflect.Descriptor instead.
func (*CreateLendingRequest) Descriptor() ([]byte, []int) {
	return file_lending_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLendingRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *CreateLendingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Lending struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BookId     string               `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	UserId     string               `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status     string               `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ReturnDate *timestamp.Timestamp `protobuf:"bytes,5,opt,name=return_date,json=returnDate,proto3" json:"return_date,omitempty"`
}

func (x *Lending) Reset() {
	*x = Lending{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lending_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lending) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lending) ProtoMessage() {}

func (x *Lending) ProtoReflect() protoreflect.Message {
	mi := &file_lending_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lending.ProtoReflect.Descriptor instead.
func (*Lending) Descriptor() ([]byte, []int) {
	return file_lending_proto_rawDescGZIP(), []int{1}
}

func (x *Lending) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lending) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *Lending) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Lending) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Lending) GetReturnDate() *timestamp.Timestamp {
	if x != nil {
		return x.ReturnDate
	}
	return nil
}

type FetchLendingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagination     *LendingPaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	BookId         string                    `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	UserId         string                    `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status         string                    `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	PassReturnDate bool                      `protobuf:"varint,5,opt,name=pass_return_date,json=passReturnDate,proto3" json:"pass_return_date,omitempty"`
}

func (x *FetchLendingRequest) Reset() {
	*x = FetchLendingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lending_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchLendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchLendingRequest) ProtoMessage() {}

func (x *FetchLendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lending_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchLendingRequest.ProtoReflect.Descriptor instead.
func (*FetchLendingRequest) Descriptor() ([]byte, []int) {
	return file_lending_proto_rawDescGZIP(), []int{2}
}

func (x *FetchLendingRequest) GetPagination() *LendingPaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *FetchLendingRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *FetchLendingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FetchLendingRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FetchLendingRequest) GetPassReturnDate() bool {
	if x != nil {
		return x.PassReturnDate
	}
	return false
}

type FetchLendingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagination *LendingPaginationResponse `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Lendings   []*Lending                 `protobuf:"bytes,2,rep,name=lendings,proto3" json:"lendings,omitempty"`
}

func (x *FetchLendingResponse) Reset() {
	*x = FetchLendingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lending_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchLendingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchLendingResponse) ProtoMessage() {}

func (x *FetchLendingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lending_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchLendingResponse.ProtoReflect.Descriptor instead.
func (*FetchLendingResponse) Descriptor() ([]byte, []int) {
	return file_lending_proto_rawDescGZIP(), []int{3}
}

func (x *FetchLendingResponse) GetPagination() *LendingPaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *FetchLendingResponse) GetLendings() []*Lending {
	if x != nil {
		return x.Lendings
	}
	return nil
}

type LendingPaginationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page  int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *LendingPaginationRequest) Reset() {
	*x = LendingPaginationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lending_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LendingPaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LendingPaginationRequest) ProtoMessage() {}

func (x *LendingPaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lending_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LendingPaginationRequest.ProtoReflect.Descriptor instead.
func (*LendingPaginationRequest) Descriptor() ([]byte, []int) {
	return file_lending_proto_rawDescGZIP(), []int{4}
}

func (x *LendingPaginationRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *LendingPaginationRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type LendingPaginationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit    int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page     int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	LastPage int32 `protobuf:"varint,3,opt,name=last_page,json=lastPage,proto3" json:"last_page,omitempty"`
	Total    int32 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *LendingPaginationResponse) Reset() {
	*x = LendingPaginationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lending_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LendingPaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LendingPaginationResponse) ProtoMessage() {}

func (x *LendingPaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lending_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LendingPaginationResponse.ProtoReflect.Descriptor instead.
func (*LendingPaginationResponse) Descriptor() ([]byte, []int) {
	return file_lending_proto_rawDescGZIP(), []int{5}
}

func (x *LendingPaginationResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *LendingPaginationResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *LendingPaginationResponse) GetLastPage() int32 {
	if x != nil {
		return x.LastPage
	}
	return 0
}

func (x *LendingPaginationResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RenewLendingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RenewLendingRequest) Reset() {
	*x = RenewLendingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lending_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenewLendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewLendingRequest) ProtoMessage() {}

func (x *RenewLendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lending_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewLendingRequest.ProtoReflect.Descriptor instead.
func (*RenewLendingRequest) Descriptor() ([]byte, []int) {
	return file_lending_proto_rawDescGZIP(), []int{6}
}

func (x *RenewLendingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FinishLendingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FinishLendingRequest) Reset() {
	*x = FinishLendingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lending_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishLendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishLendingRequest) ProtoMessage() {}

func (x *FinishLendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lending_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishLendingRequest.ProtoReflect.Descriptor instead.
func (*FinishLendingRequest) Descriptor() ([]byte, []int) {
	return file_lending_proto_rawDescGZIP(), []int{7}
}

func (x *FinishLendingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_lending_proto protoreflect.FileDescriptor

var file_lending_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x6c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x48, 0x0a, 0x14, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0xa0, 0x01, 0x0a, 0x07, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3b, 0x0a, 0x0b, 0x72, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x72, 0x65, 0x74, 0x75,
	0x72, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x22, 0xcc, 0x01, 0x0a, 0x13, 0x46, 0x65, 0x74, 0x63, 0x68,
	0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x41,
	0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x4c, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x28, 0x0a, 0x10, 0x70,
	0x61, 0x73, 0x73, 0x5f, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x70, 0x61, 0x73, 0x73, 0x52, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x44, 0x61, 0x74, 0x65, 0x22, 0x88, 0x01, 0x0a, 0x14, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4c,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42,
	0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x4c, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x08, 0x6c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x4c,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x6c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73,
	0x22, 0x44, 0x0a, 0x18, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x78, 0x0a, 0x19, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x50, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x22, 0x25, 0x0a, 0x13, 0x52, 0x65, 0x6e, 0x65, 0x77, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x26, 0x0a, 0x14, 0x46, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32,
	0xa9, 0x02, 0x0a, 0x0e, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x42, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x12, 0x1d, 0x2e, 0x6c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x10, 0x2e, 0x6c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x4c, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0c, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4c,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x2e, 0x6c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x46,
	0x65, 0x74, 0x63, 0x68, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0c, 0x52, 0x65, 0x6e, 0x65, 0x77, 0x4c, 0x65,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x2e, 0x6c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x2e,
	0x52, 0x65, 0x6e, 0x65, 0x77, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x6c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x4c, 0x65,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0d, 0x46, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x1d, 0x2e, 0x6c, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x6c, 0x65, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x2e, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x70,
	0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lending_proto_rawDescOnce sync.Once
	file_lending_proto_rawDescData = file_lending_proto_rawDesc
)

func file_lending_proto_rawDescGZIP() []byte {
	file_lending_proto_rawDescOnce.Do(func() {
		file_lending_proto_rawDescData = protoimpl.X.CompressGZIP(file_lending_proto_rawDescData)
	})
	return file_lending_proto_rawDescData
}

var file_lending_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_lending_proto_goTypes = []interface{}{
	(*CreateLendingRequest)(nil),      // 0: lending.CreateLendingRequest
	(*Lending)(nil),                   // 1: lending.Lending
	(*FetchLendingRequest)(nil),       // 2: lending.FetchLendingRequest
	(*FetchLendingResponse)(nil),      // 3: lending.FetchLendingResponse
	(*LendingPaginationRequest)(nil),  // 4: lending.LendingPaginationRequest
	(*LendingPaginationResponse)(nil), // 5: lending.LendingPaginationResponse
	(*RenewLendingRequest)(nil),       // 6: lending.RenewLendingRequest
	(*FinishLendingRequest)(nil),      // 7: lending.FinishLendingRequest
	(*timestamp.Timestamp)(nil),       // 8: google.protobuf.Timestamp
}
var file_lending_proto_depIdxs = []int32{
	8, // 0: lending.Lending.return_date:type_name -> google.protobuf.Timestamp
	4, // 1: lending.FetchLendingRequest.pagination:type_name -> lending.LendingPaginationRequest
	5, // 2: lending.FetchLendingResponse.pagination:type_name -> lending.LendingPaginationResponse
	1, // 3: lending.FetchLendingResponse.lendings:type_name -> lending.Lending
	0, // 4: lending.LendingService.CreateLending:input_type -> lending.CreateLendingRequest
	2, // 5: lending.LendingService.FetchLending:input_type -> lending.FetchLendingRequest
	6, // 6: lending.LendingService.RenewLending:input_type -> lending.RenewLendingRequest
	7, // 7: lending.LendingService.FinishLending:input_type -> lending.FinishLendingRequest
	1, // 8: lending.LendingService.CreateLending:output_type -> lending.Lending
	3, // 9: lending.LendingService.FetchLending:output_type -> lending.FetchLendingResponse
	1, // 10: lending.LendingService.RenewLending:output_type -> lending.Lending
	1, // 11: lending.LendingService.FinishLending:output_type -> lending.Lending
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_lending_proto_init() }
func file_lending_proto_init() {
	if File_lending_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lending_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLendingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lending_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lending); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lending_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchLendingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lending_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchLendingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lending_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LendingPaginationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lending_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LendingPaginationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lending_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenewLendingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lending_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishLendingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lending_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lending_proto_goTypes,
		DependencyIndexes: file_lending_proto_depIdxs,
		MessageInfos:      file_lending_proto_msgTypes,
	}.Build()
	File_lending_proto = out.File
	file_lending_proto_rawDesc = nil
	file_lending_proto_goTypes = nil
	file_lending_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LendingServiceClient is the client API for LendingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LendingServiceClient interface {
	CreateLending(ctx context.Context, in *CreateLendingRequest, opts ...grpc.CallOption) (*Lending, error)
	FetchLending(ctx context.Context, in *FetchLendingRequest, opts ...grpc.CallOption) (*FetchLendingResponse, error)
	RenewLending(ctx context.Context, in *RenewLendingRequest, opts ...grpc.CallOption) (*Lending, error)
	FinishLending(ctx context.Context, in *FinishLendingRequest, opts ...grpc.CallOption) (*Lending, error)
}

type lendingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLendingServiceClient(cc grpc.ClientConnInterface) LendingServiceClient {
	return &lendingServiceClient{cc}
}

func (c *lendingServiceClient) CreateLending(ctx context.Context, in *CreateLendingRequest, opts ...grpc.CallOption) (*Lending, error) {
	out := new(Lending)
	err := c.cc.Invoke(ctx, "/lending.LendingService/CreateLending", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lendingServiceClient) FetchLending(ctx context.Context, in *FetchLendingRequest, opts ...grpc.CallOption) (*FetchLendingResponse, error) {
	out := new(FetchLendingResponse)
	err := c.cc.Invoke(ctx, "/lending.LendingService/FetchLending", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lendingServiceClient) RenewLending(ctx context.Context, in *RenewLendingRequest, opts ...grpc.CallOption) (*Lending, error) {
	out := new(Lending)
	err := c.cc.Invoke(ctx, "/lending.LendingService/RenewLending", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lendingServiceClient) FinishLending(ctx context.Context, in *FinishLendingRequest, opts ...grpc.CallOption) (*Lending, error) {
	out := new(Lending)
	err := c.cc.Invoke(ctx, "/lending.LendingService/FinishLending", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LendingServiceServer is the server API for LendingService service.
type LendingServiceServer interface {
	CreateLending(context.Context, *CreateLendingRequest) (*Lending, error)
	FetchLending(context.Context, *FetchLendingRequest) (*FetchLendingResponse, error)
	RenewLending(context.Context, *RenewLendingRequest) (*Lending, error)
	FinishLending(context.Context, *FinishLendingRequest) (*Lending, error)
}

// UnimplementedLendingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLendingServiceServer struct {
}

func (*UnimplementedLendingServiceServer) CreateLending(context.Context, *CreateLendingRequest) (*Lending, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLending not implemented")
}
func (*UnimplementedLendingServiceServer) FetchLending(context.Context, *FetchLendingRequest) (*FetchLendingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchLending not implemented")
}
func (*UnimplementedLendingServiceServer) RenewLending(context.Context, *RenewLendingRequest) (*Lending, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenewLending not implemented")
}
func (*UnimplementedLendingServiceServer) FinishLending(context.Context, *FinishLendingRequest) (*Lending, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishLending not implemented")
}

func RegisterLendingServiceServer(s *grpc.Server, srv LendingServiceServer) {
	s.RegisterService(&_LendingService_serviceDesc, srv)
}

func _LendingService_CreateLending_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLendingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LendingServiceServer).CreateLending(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lending.LendingService/CreateLending",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LendingServiceServer).CreateLending(ctx, req.(*CreateLendingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LendingService_FetchLending_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchLendingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LendingServiceServer).FetchLending(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lending.LendingService/FetchLending",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LendingServiceServer).FetchLending(ctx, req.(*FetchLendingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LendingService_RenewLending_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewLendingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LendingServiceServer).RenewLending(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lending.LendingService/RenewLending",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LendingServiceServer).RenewLending(ctx, req.(*RenewLendingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LendingService_FinishLending_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishLendingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LendingServiceServer).FinishLending(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lending.LendingService/FinishLending",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LendingServiceServer).FinishLending(ctx, req.(*FinishLendingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LendingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lending.LendingService",
	HandlerType: (*LendingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLending",
			Handler:    _LendingService_CreateLending_Handler,
		},
		{
			MethodName: "FetchLending",
			Handler:    _LendingService_FetchLending_Handler,
		},
		{
			MethodName: "RenewLending",
			Handler:    _LendingService_RenewLending_Handler,
		},
		{
			MethodName: "FinishLending",
			Handler:    _LendingService_FinishLending_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lending.proto",
}
